config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

packages:
   package: Datavault-UK/dbtvault

dbt_postgress:
  outputs:
    dev:
      type: postgres
      threads: 6
      host: db2.mpkazantsev.ru
      port: 5432
      user: postgres
      pass: '5555'
      dbname: demo
      schema: dbt_vault
  target: dev